let player_target_stats = /*Ready to Update*/ {
    name: null,
    role: null,
    level: 0,
    exp: 0,
    defense_points: 0,
    health_points: 0,
    speed_points: 0,
    agility_points: 0,
    strength_points: 0,
    range_damage_points: 0,
    hand_damage_points: 0,
    intelectual_points: 0,
    stamina_points: 0,
    concentration_points: 0, 
    anger_points:0,
    pride_points:0,
    turns_stunned: 0,
  };